'use strict';

/** AI4 Website Design Studio — Creative Systems Generator V7.2 */
const Anthropic = require('@anthropic-ai/sdk');
const MODEL = process.env.ANTHROPIC_MODEL || 'claude-sonnet-4-6';
const AI_TIMEOUT_MS = Number(process.env.AI4_AI_TIMEOUT_MS || 12000);
const MAX_TOKENS = Number(process.env.AI4_PLATINUM_MAX_TOKENS || 8000);
const HEADERS = {'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const SYSTEMS = [
  {id:'command',name:'Command Center',bg:'#030816',bg2:'#0b2038',accent:'#4de1ff',accent2:'#d6ff6b',light:false},
  {id:'editorial',name:'Editorial Authority',bg:'#f7f2e8',bg2:'#e6dac8',accent:'#123a5a',accent2:'#b7791f',light:true},
  {id:'cinematic',name:'Cinematic Split',bg:'#100614',bg2:'#27113a',accent:'#ff5c8a',accent2:'#ffc857',light:false},
  {id:'bento',name:'Precision Bento',bg:'#07111f',bg2:'#101e32',accent:'#68a7ff',accent2:'#9df7ca',light:false}
];
function clean(v,f=''){if(Array.isArray(v))return v.map(x=>clean(x)).filter(Boolean).join(', ')||f;if(v===null||v===undefined)return f;const s=String(v).trim();return s||f}
function esc(v){return clean(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function parse(b){try{return JSON.parse(b||'{}')}catch{return {}}}
function pick(o,ks,f=''){for(const k of ks){const v=k.split('.').reduce((a,p)=>a&&a[p]!==undefined?a[p]:undefined,o);const s=clean(v);if(s)return s}return f}
function slug(v){return clean(v,'your-business').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,42)||'your-business'}
function normalize(p){const r=(p&&(p.answers||p.rawAnswers||p.siteData||p.brief||p))||{},c=r.contact||r.contactInfo||{},s=r.social||r.socialLinks||{};return{businessName:pick(r,['businessName','business_name','brandName','companyName','name'],'Your Business'),whatYouDo:pick(r,['whatYouDo','businessDescription','description','q2_whatYouDo','what','services'],'A premium business serving customers with professional solutions.'),customers:pick(r,['customers','idealCustomers','targetAudience','q3_customers','who','audience'],'customers who value trust, clarity, and a professional experience'),differentiators:pick(r,['differentiators','whatMakesDifferent','uniqueValue','q4_differentiators','diff','whyDifferent'],'clear communication, dependable service, and a polished customer experience'),extras:pick(r,['extras','optionalNotes','anythingElse','q7_extras','else','notes'],''),primaryCta:pick(r,['primaryCta','ctaText','cta','callToAction'],'Contact Us'),phone:clean(r.phone||r.phoneNumber||c.phone),email:clean(r.email||r.contactEmail||c.email),address:clean(r.address||r.location||r.serviceArea||c.address),website:clean(r.website||r.url||c.website),facebook:clean(r.facebook||s.facebook),instagram:clean(r.instagram||s.instagram),linkedin:clean(r.linkedin||s.linkedin),websiteType:pick(r,['websiteType','type','siteType'],'business')}}
function industry(a){const t=`${a.businessName} ${a.whatYouDo} ${a.customers} ${a.differentiators} ${a.extras}`.toLowerCase();if(/ai|software|automation|technology|app|saas|cyber|cloud|data|crm|voice agent|contracting intelligence|workflow/.test(t))return'Technology / AI Services';if(/consult|accounting|tax|legal|law|insurance|real estate|broker/.test(t))return'Professional Services';if(/restaurant|food|broiler|grill|catering|chef|bbq|menu|kitchen/.test(t))return'Restaurant / Food Service';if(/construction|contractor|hvac|plumb|electric|roof|repair|remodel/.test(t))return'Construction / Skilled Trades';if(/nonprofit|ministry|church|community|foundation|outreach/.test(t))return'Community / Nonprofit';return'Premium Local Business'}
function brief(a){const ind=industry(a);return{businessName:a.businessName,industry:ind,marketPosition:ind==='Technology / AI Services'?'modern technical operator turning complexity into business advantage':'premium brand that looks established, credible, and easy to choose',sectionPlan:['nav','hero','solutions','advantage','process','cta','contact','footer']}}
function hash(s){let h=0;for(let i=0;i<s.length;i++)h=Math.imul(31,h)+s.charCodeAt(i)|0;return Math.abs(h)}
function chooseSystem(a,b){const req=clean(b.styleSystem);if(req){const f=SYSTEMS.find(s=>s.id===req||s.name.toLowerCase()===req.toLowerCase());if(f)return f}const mode=clean(b.mode,'full');const seed=clean(b.seed||b.variationSeed||b.requestId,'');const basis=`${a.businessName}|${a.whatYouDo}|${mode}|${seed}|${Date.now()}|${Math.random()}`;return mode==='design'||mode==='new-design'?SYSTEMS[hash(basis)%SYSTEMS.length]:SYSTEMS[hash(`${a.businessName}|${a.whatYouDo}`)%SYSTEMS.length]}
function products(a){const raw=`${a.whatYouDo}|${a.extras}`.split(/\||\n|;|•/).map(clean).filter(x=>x.length>12),d=['Workflow Automation','Lead Management','Conversational AI','Opportunity Intelligence','Digital Operations'];const out=raw.slice(0,5);while(out.length<5)out.push(d[out.length]);return out}
function countSections(h){return(clean(h).match(/<section\b/gi)||[]).length}
function isComplete(h){const s=clean(h),l=s.toLowerCase();return l.startsWith('<!doctype html')&&l.includes('</html>')&&s.length>4500&&countSections(s)>=4}
function validate(h){const flags=[];let score=100;if(clean(h).length<6000){score-=10;flags.push('Generated HTML is short')}if(countSections(h)<5){score-=10;flags.push('Fewer than 5 sections')}if(!/<form[^>]+data-netlify=["']true["']/i.test(h)){score-=8;flags.push('Netlify form missing')}if(!/@media/i.test(h)){score-=6;flags.push('Responsive media query missing')}score=Math.max(0,Math.min(100,score));return{score,status:score>=90?'Platinum Ready':score>=75?'Complete Website Preview':'Needs Review',flags,sectionCount:countSections(h),generatedLength:clean(h).length}}
const ARCHETYPES=[
  'Asymmetric editorial — an oversized off-center display headline, magazine-style column shifts, large negative space, hairline rules, imagery/text blocks that break the grid on purpose',
  'Cinematic full-bleed — a layered atmospheric hero with depth, floating cards/panels, dramatic scale contrast, a moving marquee ribbon, bold gradient stage',
  'Precision bento grid — modular tiles of varying span, dense rhythmic composition, monospace accents, a dashboard-like feel that still sells',
  'Refined brutalist — heavy confident type, hard borders, high-contrast blocks, exposed grid lines, unconventional but premium',
  'Boutique luxury — serif display type, soft paper/stone tones, fine dividers, slow elegant spacing, a high-end retail or hospitality feel',
  'Kinetic tech console — dark command-center aesthetic, neon accent glow, terminal/data motifs, sharp panels and counters'
];
const TYPE_SYSTEMS=['Syne + Inter','Space Grotesk + Inter','Sora + IBM Plex Sans','Archivo + Manrope','Fraunces + Inter','Cormorant Garamond + DM Sans','Bricolage Grotesque + Inter'];
const PALETTES=['deep ink navy with electric cyan and acid-lime accents','warm bone/cream paper with deep teal and burnt amber','near-black plum with hot magenta and gold','charcoal and white with a single saturated accent and lots of air','midnight blue with iced blue and mint','off-white gallery with black type and one bold accent','forest green with cream and copper'];
const MOODS=['confident and authoritative','bold and unconventional','elegant and premium','energetic and modern','calm, editorial, and trustworthy'];
const MOTIONS=['subtle scroll reveals and hover lifts','a moving marquee and gentle gradient drift','sticky section transitions and animated counters','restraint over animation — let the layout carry it'];
function directives(a,b,body){const mode=clean(body.mode,'full');const fresh=mode==='design'||mode==='new-design'||clean(body.regenerate)==='true'||clean(body.seed)||clean(body.variationSeed);const base=`${a.businessName}|${a.whatYouDo}`;const seed=fresh?`${base}|${clean(body.seed||body.variationSeed||body.requestId,'')}|${Date.now()}|${Math.random()}`:base;const h=hash(seed);return{archetype:ARCHETYPES[h%ARCHETYPES.length],type:TYPE_SYSTEMS[(h>>3)%TYPE_SYSTEMS.length],palette:PALETTES[(h>>6)%PALETTES.length],mood:MOODS[(h>>9)%MOODS.length],motion:MOTIONS[(h>>11)%MOTIONS.length]}}
function prompt(a,b,d){return `You are an award-winning art director and senior front-end designer. Design ONE complete, original, standalone promotional website for a real business. It must look bespoke and hand-crafted — NOT a generic template, NOT a typical SaaS landing page. Someone should look at it and think a human designer made it specifically for this company.

BUSINESS
- Name: ${a.businessName}
- Industry: ${b.industry}
- What they do: ${a.whatYouDo}
- Ideal customer: ${a.customers}
- Differentiator: ${a.differentiators}
- Primary call to action: ${a.primaryCta}${a.phone?`\n- Phone: ${a.phone}`:''}${a.email?`\n- Email: ${a.email}`:''}${a.address?`\n- Location: ${a.address}`:''}

CREATIVE DIRECTION (commit to this fully and make it unmistakable)
- Layout archetype: ${d.archetype}
- Typography: ${d.type}, loaded via Google Fonts
- Color story: ${d.palette}
- Mood: ${d.mood}
- Motion / interaction: ${d.motion}

DESIGN RULES
- Invent a distinctive visual identity for this exact business. Write a custom hero headline for THEM (never "Welcome to..."). Make every section visually different from the last — vary layout, rhythm, and emphasis.
- Write specific, persuasive copy tailored to the business and its customer. No lorem ipsum, no placeholders, no fake testimonials, no invented awards or statistics.
- At least 6 distinct sections (e.g. hero, what they do / services, the differentiator, how it works / process, a value or proof-style section, contact). Intentional asymmetry and real visual hierarchy.
- Modern CSS only: CSS variables, a clamp() type scale, grid/flex, gradients, smooth scroll, tasteful hover states, and a responsive @media layout for mobile. All CSS in a single <style> in the head. No external JS frameworks, no build tools.
- Include a working contact form EXACTLY in this form so it submits on Netlify: <form name="contact" method="POST" data-netlify="true"><input type="hidden" name="form-name" value="contact"> ...your fields... </form>

OUTPUT
- Return ONLY the HTML document, starting with <!DOCTYPE html> and ending with </html>.
- No markdown, no code fences, no commentary before or after the HTML.`}
async function callClaudeFast(p){if(!process.env.ANTHROPIC_API_KEY)throw new Error('ANTHROPIC_API_KEY not set');const client=new Anthropic({apiKey:process.env.ANTHROPIC_API_KEY}),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),AI_TIMEOUT_MS);try{const r=await client.messages.create({model:MODEL,max_tokens:MAX_TOKENS,messages:[{role:'user',content:p}]},{signal:controller.signal});let h=(r.content||[]).filter(x=>!x.type||x.type==='text').map(x=>x.text||'').join('\n').trim();h=h.replace(/^```html\s*/i,'').replace(/^```\s*/i,'').replace(/\s*```$/i,'').trim();const st=h.toLowerCase().indexOf('<!doctype html');if(st>0)h=h.slice(st);const en=h.toLowerCase().lastIndexOf('</html>');if(en>=0)h=h.slice(0,en+7);return h}finally{clearTimeout(timer)}}
function css(sys){const text=sys.light?'#101827':'#f8fbff',muted=sys.light?'#536173':'#a7b5c8',panel=sys.light?'rgba(255,255,255,.72)':'rgba(255,255,255,.075)',line=sys.light?'rgba(15,23,42,.13)':'rgba(255,255,255,.14)';return`<style>:root{--bg:${sys.bg};--bg2:${sys.bg2};--text:${text};--muted:${muted};--panel:${panel};--line:${line};--accent:${sys.accent};--accent2:${sys.accent2}}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:Inter,system-ui,sans-serif;background:radial-gradient(circle at 18% 4%,var(--accent),transparent 34%),linear-gradient(135deg,var(--bg),var(--bg2));color:var(--text);line-height:1.65}a{color:inherit;text-decoration:none}.wrap{max-width:1180px;margin:auto;padding:0 24px}.btn{display:inline-flex;align-items:center;justify-content:center;border-radius:999px;background:linear-gradient(135deg,#fff,var(--accent));color:#06101a;padding:14px 22px;font-weight:900;border:0}.ghost{background:transparent;color:var(--text);border:1px solid var(--line)}nav{position:sticky;top:0;z-index:10;background:var(--bg);border-bottom:1px solid var(--line)}.nav{min-height:78px;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{font-family:Syne,sans-serif;font-size:25px;font-weight:800}.navlinks{display:flex;align-items:center;gap:18px;color:var(--muted);font-weight:800;font-size:14px}section{padding:82px 0}.eyebrow{letter-spacing:.16em;text-transform:uppercase;color:var(--accent);font-size:12px;font-weight:900}.lead{font-size:clamp(18px,2vw,23px);color:var(--muted);max-width:820px}.kicker{font-family:Syne,sans-serif;font-size:clamp(34px,4vw,54px);line-height:1;letter-spacing:-.045em;margin:0}.cards{display:grid;gap:18px}.card{border:1px solid var(--line);border-radius:26px;padding:28px;background:var(--panel)}.card span{color:var(--accent);font-weight:900}.card h3{font-family:Syne,sans-serif;font-size:25px;line-height:1.05;margin:16px 0}.split{display:grid;grid-template-columns:.86fr 1.14fr;gap:42px;align-items:start}.list{display:grid;gap:14px}.item{border-left:3px solid var(--accent);padding:12px 0 12px 18px;color:var(--muted);font-size:18px}.contact{display:grid;grid-template-columns:.85fr 1.15fr;gap:28px}.contact-box,form{border:1px solid var(--line);border-radius:30px;background:var(--panel);padding:30px}form{display:grid;gap:14px}input,textarea{width:100%;border:1px solid var(--line);background:var(--bg);color:var(--text);border-radius:16px;padding:15px;font:inherit}textarea{min-height:130px}.footer{padding:32px 0;border-top:1px solid var(--line);color:var(--muted);font-size:14px}@media(max-width:980px){.split,.contact{grid-template-columns:1fr}.nav{align-items:flex-start;flex-direction:column;padding:18px 0}.navlinks{flex-wrap:wrap}}</style>`}
function contact(a,n,cta){return`<section id="contact"><div class="wrap contact"><div class="contact-box"><h2 class="kicker">Contact ${n}</h2>${a.phone?`<p><b>Phone:</b> ${esc(a.phone)}</p>`:''}${a.email?`<p><b>Email:</b> ${esc(a.email)}</p>`:''}${a.address?`<p><b>Location:</b> ${esc(a.address)}</p>`:''}<p>Tell us what you want to streamline, automate, or organize next.</p></div><form name="contact" method="POST" data-netlify="true"><input type="hidden" name="form-name" value="contact"><input name="name" placeholder="Your name" required><input name="email" type="email" placeholder="Email address" required><input name="phone" placeholder="Phone number"><textarea name="message" placeholder="Tell us what you need"></textarea><button class="btn" type="submit">${cta}</button></form></div></section>`}
function shell(a,sys,body){const n=esc(a.businessName),cta=esc(a.primaryCta),y=new Date().getFullYear();return`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${n}</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700;800;900&family=Syne:wght@700;800&display=swap" rel="stylesheet">${css(sys)}</head><body><nav><div class="wrap nav"><div class="brand">${n}</div><div class="navlinks"><a href="#solutions">Solutions</a><a href="#advantage">Advantage</a><a href="#contact" class="btn">${cta}</a></div></div></nav><main>${body}${contact(a,n,cta)}</main><footer class="footer"><div class="wrap">© ${y} ${n}. Built with AI4 Website Design.</div></footer></body></html>`}
function command(a,b,sys,it){const n=esc(a.businessName),w=esc(a.whatYouDo),who=esc(a.customers),d=esc(a.differentiators),cta=esc(a.primaryCta);return`<style>.hero{min-height:calc(100vh - 78px);display:grid;align-items:center}.command{display:grid;grid-template-columns:1fr 360px;gap:36px}.hero h1{font-family:Syne,sans-serif;font-size:clamp(58px,8vw,118px);line-height:.86;letter-spacing:-.08em;margin:18px 0}.console{border:1px solid var(--line);border-radius:28px;background:rgba(0,0,0,.22);padding:22px;display:grid;gap:14px}.console div{border-bottom:1px solid var(--line);padding:12px 0}.solutions{grid-template-columns:repeat(2,1fr)}.ops{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}@media(max-width:980px){.command,.solutions,.ops{grid-template-columns:1fr}}</style><section class="hero"><div class="wrap command"><div><div class="eyebrow">${esc(b.industry)} · ${esc(sys.name)}</div><h1>${n}</h1><p class="lead">${w}</p><p class="lead">Built for ${who}, this system brings automation, intelligence, and workflow clarity into one operating view.</p><p><a class="btn" href="#contact">${cta}</a> <a class="btn ghost" href="#solutions">View Systems</a></p></div><aside class="console"><div><b>Focus</b><p>${who}</p></div><div><b>Advantage</b><p>${d}</p></div><div><b>Action</b><p>${cta}</p></div></aside></div></section><section id="solutions"><div class="wrap split"><h2 class="kicker">A command layer for business movement.</h2><div class="cards solutions">${it.slice(0,4).map((x,i)=>`<article class="card"><span>0${i+1}</span><h3>${esc(x)}</h3><p>Organize the workflow, reduce manual follow-up, and move the customer toward the next action.</p></article>`).join('')}</div></div></section><section id="advantage"><div class="wrap ops">${['Capture business interest','Sort the need clearly','Surface the next action','Keep the workflow moving'].map((x,i)=>`<article class="card"><span>0${i+1}</span><h3>${x}</h3></article>`).join('')}</div></section><section><div class="wrap split"><h2 class="kicker">Why ${n} stands out.</h2><div class="list"><div class="item">${d}</div><div class="item">Built around practical business outcomes, not generic website language.</div><div class="item">Structured to show intelligence, operational value, and next-step clarity.</div></div></div></section><section><div class="wrap"><div class="card"><h2 class="kicker">Ready to put the system to work?</h2><p class="lead">Start with a direct conversation about the workflow you want to streamline.</p><a class="btn" href="#contact">${cta}</a></div></div></section>`}
function editorial(a,b,sys,it){const n=esc(a.businessName),w=esc(a.whatYouDo),who=esc(a.customers),d=esc(a.differentiators),cta=esc(a.primaryCta);return`<style>.ed{padding:110px 0 70px}.ed h1{font-family:Syne,sans-serif;font-size:clamp(62px,10vw,146px);line-height:.82;letter-spacing:-.09em;max-width:1120px;margin:18px 0}.edcopy{display:grid;grid-template-columns:.7fr 1.3fr;gap:34px;border-top:1px solid var(--line);padding-top:28px}.feature{display:grid;grid-template-columns:120px 1fr;gap:28px;border-bottom:1px solid var(--line);padding:24px 0}.feature b{font-size:42px;font-family:Syne,sans-serif;color:var(--accent2)}.quote{border-radius:34px;background:var(--panel);border:1px solid var(--line);padding:48px}.quote p{font-family:Syne,sans-serif;font-size:clamp(30px,4vw,54px);line-height:1}@media(max-width:980px){.edcopy,.feature{grid-template-columns:1fr}}</style><section class="ed"><div class="wrap"><div class="eyebrow">${esc(b.industry)} · ${esc(sys.name)}</div><h1>${n} turns business complexity into a cleaner operating path.</h1><div class="edcopy"><p>${esc(b.marketPosition)}</p><div><p class="lead">${w}</p><p class="lead">Designed for ${who}, the page explains the offer with confidence and moves buyers toward a direct conversation.</p><p><a class="btn" href="#contact">${cta}</a></p></div></div></div></section><section id="solutions"><div class="wrap">${it.slice(0,4).map((x,i)=>`<article class="feature"><b>0${i+1}</b><div><h2>${esc(x)}</h2><p>${i===0?w:i===1?`Built for ${who}.`:i===2?`The difference is ${d}.`:'A clean path from interest to action.'}</p></div></article>`).join('')}</div></section><section id="advantage"><div class="wrap quote"><p>${n} gives visitors a sharper reason to trust, understand, and act.</p><div class="list"><div class="item">${d}</div><div class="item">Clear sections replace generic filler with specific business value.</div><div class="item">The CTA is visible, direct, and repeated at the right moments.</div></div></div></section><section><div class="wrap split"><h2 class="kicker">From first impression to action.</h2><div class="cards">${['Understand','Compare','Trust','Contact'].map((x,i)=>`<article class="card"><span>0${i+1}</span><h3>${x}</h3><p>The visitor gets the right message at the right point in the page.</p></article>`).join('')}</div></div></section>`}
function cinematic(a,b,sys,it){const n=esc(a.businessName),w=esc(a.whatYouDo),who=esc(a.customers),d=esc(a.differentiators),cta=esc(a.primaryCta);return`<style>.cine{min-height:calc(100vh - 78px);display:grid;grid-template-columns:1.2fr .8fr}.copy{padding:90px clamp(24px,6vw,84px);display:flex;flex-direction:column;justify-content:center}.copy h1{font-family:Syne,sans-serif;font-size:clamp(58px,9vw,132px);line-height:.84;letter-spacing:-.085em;margin:18px 0}.stage{position:relative;min-height:560px;background:radial-gradient(circle at 50% 45%,var(--accent),transparent 28%),linear-gradient(145deg,var(--bg2),var(--bg));overflow:hidden}.stage:before{content:'';position:absolute;inset:10%;border:1px solid var(--line);border-radius:48px;transform:rotate(-7deg)}.ribbon{display:flex;gap:14px;overflow:hidden;border-block:1px solid var(--line);padding:18px 0;color:var(--accent2);font-weight:900;text-transform:uppercase;letter-spacing:.12em}.ribbon span{white-space:nowrap}.story{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.story .card:first-child{grid-column:span 2}@media(max-width:980px){.cine,.story{grid-template-columns:1fr}.story .card:first-child{grid-column:auto}.stage{min-height:300px}}</style><section class="cine"><div class="copy"><div class="eyebrow">${esc(sys.name)}</div><h1>${n}</h1><p class="lead">${w}</p><p class="lead">For ${who}, better business movement starts with clarity, intelligence, and action.</p><p><a class="btn" href="#contact">${cta}</a></p></div><div class="stage"></div></section><div class="ribbon">${it.concat(it).map(x=>`<span>${esc(x)}</span>`).join('')}</div><section id="solutions"><div class="wrap story"><article class="card"><span>01</span><h2 class="kicker">The offer is built around movement.</h2><p class="lead">${d}</p></article>${it.slice(0,4).map((x,i)=>`<article class="card"><span>0${i+2}</span><h3>${esc(x)}</h3><p>Give the customer a reason to keep moving forward.</p></article>`).join('')}</div></section><section id="advantage"><div class="wrap split"><h2 class="kicker">Why the story lands.</h2><div class="list"><div class="item">The visual direction is bold and memorable instead of template-safe.</div><div class="item">The message is centered on ${who}.</div><div class="item">${d}</div></div></div></section><section><div class="wrap"><div class="card"><h2 class="kicker">Start the conversation.</h2><p class="lead">See where ${n} can make your workflow more intelligent and easier to act on.</p><a class="btn" href="#contact">${cta}</a></div></div></section>`}
function bento(a,b,sys,it){const n=esc(a.businessName),w=esc(a.whatYouDo),who=esc(a.customers),d=esc(a.differentiators),cta=esc(a.primaryCta);return`<style>.gridhero{padding:96px 0}.gridhero h1{font-family:Syne,sans-serif;font-size:clamp(56px,8vw,120px);line-height:.88;letter-spacing:-.08em;margin:18px 0}.bento{display:grid;grid-template-columns:1.1fr .9fr .9fr;grid-auto-rows:minmax(180px,auto);gap:16px}.bento .big{grid-row:span 2}.matrix{display:grid;grid-template-columns:repeat(5,1fr);border:1px solid var(--line);border-radius:34px;overflow:hidden}.matrix div{padding:28px;border-right:1px solid var(--line);background:var(--panel)}.matrix div:last-child{border-right:0}@media(max-width:980px){.bento,.matrix{grid-template-columns:1fr}.bento .big{grid-row:auto}.matrix div{border-right:0;border-bottom:1px solid var(--line)}}</style><section class="gridhero"><div class="wrap"><div class="eyebrow">${esc(b.industry)} · ${esc(sys.name)}</div><h1>${n}</h1><p class="lead">${w}</p><p><a class="btn" href="#contact">${cta}</a> <a class="btn ghost" href="#solutions">See the Platform</a></p></div></section><section id="solutions"><div class="wrap bento"><article class="card big"><span>Core</span><h2 class="kicker">Built for ${who}.</h2><p class="lead">${d}</p></article>${it.slice(0,5).map((x,i)=>`<article class="card"><span>0${i+1}</span><h3>${esc(x)}</h3><p>Purpose-built messaging that connects the offer to a practical business outcome.</p></article>`).join('')}</div></section><section id="advantage"><div class="wrap matrix">${['Capture','Organize','Analyze','Recommend','Convert'].map(x=>`<div><h3>${x}</h3><p>Move the visitor from interest to action with clear business context.</p></div>`).join('')}</div></section><section><div class="wrap split"><h2 class="kicker">Designed to avoid sameness.</h2><div class="list"><div class="item">Different page architecture, different visual rhythm, different section treatment.</div><div class="item">${d}</div><div class="item">Built to feel like a business-specific promotional presence.</div></div></div></section>`}
function fallback(a,sys){const b=brief(a),it=products(a);let body=sys.id==='editorial'?editorial(a,b,sys,it):sys.id==='cinematic'?cinematic(a,b,sys,it):sys.id==='bento'?bento(a,b,sys,it):command(a,b,sys,it);return shell(a,sys,body)}
function ensureNetlifyForm(h,cta){if(/<form[^>]+data-netlify=["']true["']/i.test(h))return h;const block=`<section id="contact" style="padding:72px 24px;max-width:720px;margin:0 auto"><h2 style="font-size:clamp(28px,4vw,44px);margin:0 0 20px">Get in touch</h2><form name="contact" method="POST" data-netlify="true"><input type="hidden" name="form-name" value="contact"><input name="name" placeholder="Your name" required style="display:block;width:100%;margin:0 0 12px;padding:14px;border-radius:12px;border:1px solid rgba(127,127,127,.4);background:transparent;color:inherit;font:inherit"><input name="email" type="email" placeholder="Email address" required style="display:block;width:100%;margin:0 0 12px;padding:14px;border-radius:12px;border:1px solid rgba(127,127,127,.4);background:transparent;color:inherit;font:inherit"><textarea name="message" placeholder="Tell us what you need" style="display:block;width:100%;min-height:120px;margin:0 0 12px;padding:14px;border-radius:12px;border:1px solid rgba(127,127,127,.4);background:transparent;color:inherit;font:inherit"></textarea><button type="submit" style="padding:14px 28px;border-radius:999px;border:0;font-weight:800;cursor:pointer">${cta}</button></form></section>`;const i=h.toLowerCase().lastIndexOf('</body>');return i>=0?h.slice(0,i)+block+h.slice(i):h+block}
async function build(a,body){const b=brief(a),sys=chooseSystem(a,body),d=directives(a,b,body),started=Date.now();try{let h=await callClaudeFast(prompt(a,b,d));h=ensureNetlifyForm(h,esc(a.primaryCta));if(isComplete(h))return{html:h,brief:{...b,creativeSystem:sys,direction:d},quality:validate(h),source:'ai4-platinum-agent-fast'};const fb=fallback(a,sys);return{html:fb,brief:{...b,creativeSystem:sys,direction:d},quality:{...validate(fb),score:87,status:'Complete Website Preview',flags:['AI returned incomplete HTML','Creative system fallback rendered',sys.name]},source:'ai4-creative-system-fallback'}}catch(e){const fb=fallback(a,sys);return{html:fb,brief:{...b,creativeSystem:sys,direction:d},quality:{...validate(fb),score:87,status:'Complete Website Preview',flags:['AI call did not finish inside the Netlify-safe window','Creative system fallback rendered',sys.name]},source:'ai4-creative-system-fallback',error:clean(e.message||e),elapsedMs:Date.now()-started}}}
exports.handler=async(event)=>{if(event.httpMethod==='OPTIONS')return{statusCode:200,headers:HEADERS,body:''};if(event.httpMethod!=='POST')return{statusCode:405,headers:HEADERS,body:JSON.stringify({error:'Method not allowed'})};const body=parse(event.body),a=normalize(body),r=await build(a,body);return{statusCode:200,headers:HEADERS,body:JSON.stringify({success:true,source:r.source,html:r.html,builtHtml:r.html,websiteHtml:r.html,templates:[r.html],brief:{brandName:a.businessName,status:r.quality.status,qualityScore:r.quality.score,platinumCreativeBrief:r.brief},quality:r.quality,siteData:{businessName:a.businessName,business_name:a.businessName,designSystem:'AI4 Creative Systems Engine V7.2',industry:r.brief.industry,creativeSystem:r.brief.creativeSystem},meta:{generatedAt:new Date().toISOString(),slug:slug(a.businessName),model:MODEL,aiTimeoutMs:AI_TIMEOUT_MS,elapsedMs:r.elapsedMs||null,error:r.error||null}})}};
